/****** Object:  Table [pricing].[Tariffario]    Script Date: 07/07/2026 11:33:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [pricing].[Tariffario](
	[TariffarioID] [int] IDENTITY(1,1) NOT NULL,
	[Descrizione] [nvarchar](100) NULL,
	[BrandID] [smallint] NULL,
	[Codice] [nvarchar](20) NULL,
 CONSTRAINT [PK_Tariffario] PRIMARY KEY CLUSTERED 
(
	[TariffarioID] ASC
)WITH (STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UNIQUE_CODICETARIFFARIO] UNIQUE NONCLUSTERED 
(
	[Codice] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UNIQUE_DESCRIZIONETARIFFARIO] UNIQUE NONCLUSTERED 
(
	[Descrizione] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [pricing].[Tariffario]  WITH NOCHECK ADD  CONSTRAINT [FK_Tariffario_Brand] FOREIGN KEY([BrandID])
REFERENCES [dbo].[Brand] ([BrandID])
GO

ALTER TABLE [pricing].[Tariffario] CHECK CONSTRAINT [FK_Tariffario_Brand]
GO

